services:
  api:
    container_name: go-app
    build:
      context: .
      dockerfile: Dockerfile
    image: go-app
    ports:
      - 8080:8080
    env_file:
      - .env.example
    environment:
      - DATABASE_URI=postgres://postgres:password@postgres:5432/mydb?sslmode=disable
    networks:
      - go-network
    develop:
      watch:
        - path: .
          action: rebuild

  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    networks:
      - go-network

volumes:
  postgres_data:

networks:
  go-network:
    driver: bridge